// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMQlqBOrwAPHVvzTlRW-YN3JKCfjM05SI',
    appId: '1:1081102891073:web:ca72aa982fa60629cbeec0',
    messagingSenderId: '1081102891073',
    projectId: 'project-alura-cf0e8',
    authDomain: 'project-alura-cf0e8.firebaseapp.com',
    storageBucket: 'project-alura-cf0e8.appspot.com',
    measurementId: 'G-MMCBV7JYFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADRSFvZLELRH4D36QSJpH3LWKH-U-EWx8',
    appId: '1:1081102891073:android:8459f614a2b86285cbeec0',
    messagingSenderId: '1081102891073',
    projectId: 'project-alura-cf0e8',
    storageBucket: 'project-alura-cf0e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhWdvb-kmAuMKniTpX3Upqa_i96rnQBUc',
    appId: '1:1081102891073:ios:1be8707f1dcafcd1cbeec0',
    messagingSenderId: '1081102891073',
    projectId: 'project-alura-cf0e8',
    storageBucket: 'project-alura-cf0e8.appspot.com',
    iosClientId: '1081102891073-r7vduump1unmfc9ukj5pfio9v3bvpvq8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhWdvb-kmAuMKniTpX3Upqa_i96rnQBUc',
    appId: '1:1081102891073:ios:1be8707f1dcafcd1cbeec0',
    messagingSenderId: '1081102891073',
    projectId: 'project-alura-cf0e8',
    storageBucket: 'project-alura-cf0e8.appspot.com',
    iosClientId: '1081102891073-r7vduump1unmfc9ukj5pfio9v3bvpvq8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
